function T = KEfun(I1,I2,m1,m2,mb,L1,L2,g,Th1,Th2,S,dTh1,dTh2,dS,t)
%KEfun
%    T = KEfun(I1,I2,M1,M2,MB,L1,L2,G,Th1,Th2,S,dTh1,dTh2,dS,t)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 17:38:55

t2 = L1.^2;
t3 = dTh1.^2;
t4 = dTh2.^2;
t5 = -Th2;
t6 = Th1+t5;
t7 = cos(t6);
T = (I1.*t3)./2.0+(I2.*t4)./2.0+(dS.^2.*mb)./2.0+(m1.*t2.*t3)./8.0+(m2.*t2.*t3)./2.0+(mb.*t2.*t3)./2.0+(L2.^2.*m2.*t4)./8.0+(S.^2.*mb.*t4)./2.0-L1.*dS.*dTh1.*mb.*sin(t6)+(L1.*L2.*dTh1.*dTh2.*m2.*t7)./2.0+L1.*S.*dTh1.*dTh2.*mb.*t7;
