function M = Mfun(I1,I2,m1,m2,mb,L1,L2,g,Th1,Th2,S,t)
%Mfun
%    M = Mfun(I1,I2,M1,M2,MB,L1,L2,G,Th1,Th2,S,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 17:38:54

t2 = L2.*m2;
t3 = L1.^2;
t4 = S.*mb.*2.0;
t5 = -Th2;
t6 = Th1+t5;
t9 = t2+t4;
t7 = cos(t6);
t8 = sin(t6);
t10 = L1.*mb.*t8;
t12 = (L1.*t7.*t9)./2.0;
t11 = -t10;
M = reshape([I1+(m1.*t3)./4.0+m2.*t3+mb.*t3,t12,t11,t12,I2+(L2.*t2)./4.0+S.^2.*mb,0.0,t11,0.0,mb],[3,3]);
