function V = PEfun(I1,I2,m1,m2,mb,L1,L2,g,Th1,Th2,S,t)
%PEfun
%    V = PEfun(I1,I2,M1,M2,MB,L1,L2,G,Th1,Th2,S,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 17:38:55

t2 = sin(Th1);
t3 = sin(Th2);
t4 = L1.*t2;
V = g.*m2.*(t4+(L2.*t3)./2.0)+g.*mb.*(t4+S.*t3)+(g.*m1.*t4)./2.0;
